// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqkwbbzmsrjwfzqgecmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxa3diYnptc3Jqd2Z6cWdlY215Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTA5NTAsImV4cCI6MjA2MzY4Njk1MH0.YESxLqsWlhiGgW_3UtG28Il1SRPRPS3X1CinLDgwQ8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);