"""Add 'Tools' to valid employee categories

Revision ID: 377f3b0420d3
Revises: 60515998c97a
Create Date: 2025-05-25 10:31:03.213340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377f3b0420d3'
down_revision = '60515998c97a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.drop_column('position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
