"""Final Product model: add price, location, constraints

Revision ID: 60515998c97a
Revises: 8b823ea88ae5
Create Date: 2025-05-25 09:59:27.408924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60515998c97a'
down_revision = '8b823ea88ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
